services:
  django:
    build: .
    container_name: django_app
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    env_file: .env
    command: celery -A config worker --loglevel=info
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    container_name: celery_beat
    env_file: .env
    command: celery -A config beat --loglevel=info
    depends_on:
      - django
      - redis

volumes:
  postgres_data:
